# ======================
# Project Configuration
# ======================

paths:
  raw_dir: data/raw
  proc_dir: data/processed
  models_dir: models
  runs_dir: runs

data:
  text_col: text
  label_col: label
  sources:
    - ds1.csv
    - ds2.csv
    - ds3.csv
  label_canonical: {negative: 0, neutral: 1, positive: 2}

  # dataset-specific raw label -> canonical mapping
  value_to_canonical:
    ds1.csv:          
      "0": 0
      "2": 1
      "4": 2      

    ds2.csv:          
      "negative": 0
      "neutra": 1
      "neutral": 1
      "positive": 2

    ds3.csv:         
      "-1": 0
      "0": 1
      "1": 2 

  clean:
    lower: false
    replace_urls: true
    replace_mentions: true
    keep_emojis: true

  split:
    strategy: stratified 
    test_size: 0.15
    val_size: 0.15
    seed: 42

model:
  name: bert-base-uncased   # try roberta-base, bertweet-base, etc.
  num_labels: 3
  max_length: 64
  dropout: 0.1
  freeze_encoder: false     

train:
  batch_size: 64
  eval_batch_size: 128
  epochs: 5
  lr: 2e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  gradient_accumulation_steps: 1
  fp16: true
  early_stopping_patience: 3
  metric_for_best_model: f1_macro
  use_class_weights: true
  num_workers: 4 
  
logging:
  tensorboard: true
  save_every_epochs: 1
  log_level: info
